### ISSUE TITLE
undefined reference to `__imp__InterlockedCompareExchange64'

### ISSUE THREAD

**Issue by madelfagam** [RicoP/raylib-video#3]
Hi, I'm not very good at C++, so I had the problem compiling for Windows, everything worked fine for Linux. I have a MinGW-W64-builds-5.0.0 and I get an error. Do you have any idea what the problem is? I'm sorry for so stupid question.

**Comment by RicoP** [comment]
So far I only compiled the project under windows with MSVC. I never tried MinGW. I gonna look into it.

**Comment by RicoP** [comment]
So I created a new branch https://github.com/RicoP/raylib-video/tree/MinGW-fix 

Could you check out this branch and check if it still compiles under linux and MinGW? I don't have a environment right now where I can test myself.

**Comment by madelfagam** [comment]
Wow, it works! Except that my compiler threw an exception on line 222. It seems that compiler has entered the UNIX check. If you delete the entire "#elif" starting from 220 line, then everything is fine (but only for Windows, of course). Thank you so much for taking the time to do this!

**Comment by madelfagam** [comment]
And yes, it works fine under linux MinGW, just checked it.

**Comment by RicoP** [comment]
> Wow, it works! Except that my compiler threw an exception on line 222. It seems that compiler has entered the UNIX check. If you delete the entire "#elif" starting from 220 line, then everything is fine (but only for Windows, of course). Thank you so much for taking the time to do this!

What exactly is the compiler error?

**Comment by RicoP** [comment]
> Wow, it works! Except that my compiler threw an exception on line 222. It seems that compiler has entered the UNIX check. If you delete the entire "#elif" starting from 220 line, then everything is fine (but only for Windows, of course). Thank you so much for taking the time to do this!

What exactly is the compiler error?

**Comment by madelfagam** [comment]
> What exactly is the compiler error?

raylibvideo.h|222|error: 'pthread_t' was not declared in this scope

**Comment by madelfagam** [comment]
> If you delete the entire "#elif" starting from 220 line, then everything is fine (but only for Windows, of course).

I fixed it in a very ugly way
![image](https://github.com/RicoP/raylib-video/assets/59872337/f0131b95-0f25-44f4-a035-6bfbe5a01080)

**Comment by RicoP** [comment]
@madelfagam sorry for the late reply. I committed a fix and custom build scripts for MinGW into main
